name: Build and test

env:
  DOTNET_VERSION: '7.0.x'

on:
  push:
    branches:
      - '*'
      - '!master'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        working-directory: tests
        run: dotnet test --configuration Release --no-build

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Test
        working-directory: tests
        run: dotnet test --configuration Release --no-build
